### PR TITLE
Instructions for contributions and setup of the project in local

### PR DESCRIPTION
**Pull request by SoldierCorp**
What do you think?

#30

### CODE REVIEW

**Comment by SoldierCorp** [comment]
Cool and I didn't realised is not necessary to run a local server, so the changes are:

- Remove the section regarding the locally setup

Anything else?

And nope, the CSS is not supposed to be edited.

**Comment by StevenCopeland** [comment]
@nicolaihoilund Are we ready for this to be merged?

**Comment by nicolaihoilund** [comment]
The changes haven't been made yet.

**Comment by nicolaihoilund** [comment]
The CSS file just needs to be deleted now

**Pull request merged**
